 CREATE DATABASE WishList
 GO

 USE WishList
 GO


 CREATE TABLE USUARIO(
  idUsuario SMALLINT PRIMARY KEY IDENTITY,
  email VARCHAR(256) UNIQUE NOT NULL,
  senha VARCHAR(10) NOT NULL 
);
GO

CREATE TABLE DESEJO(
  idDesejo SMALLINT PRIMARY KEY IDENTITY,
  idUsuario  SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  descricao VARCHAR(500) NOT NULL,
  dataDesejo DATE
);
GO